### ISSUE TITLE
Consume REST datasources for all needed FOLIO data

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/folio-graphql#2]
# summary
- [x] blocked? (https://github.com/sul-dlss/sul-requests/issues/1460)
- [x] patron email `patron.user.personal.email`
- [x] expiration date `patron.user.expirationDate`
- [ ] borrowing limit (#33)
- [ ] eresource access (skipping this for now)
- [x] total checkouts `patron.totalLoans`
- [x] how many checkouts are recalled (`patron > loans > details > dueDateChangedByRecall`?)
- [x] how many checkouts are overdue `patron.loans.overdue`
- [x] how many total requests `patron.totalHolds` plus non-FOLIO data
- [x] how many requests are ready for pickup (calculate from `patron.holds.status` ?) (#32)
- [x] total fines/fees payable amount `patron.totalCharges.amount`
- [x] total fines/fees accruing on overdue items —  (`patron > loans > details > feesAndFines`?)

# checkouts
(for each item)
- [x] patron key
- [x] checkout status `patron.loans.item.item.status.name`
- [x] total fines accrued—  (`patron > loans > details > feesAndFines`?)
- [x] due date `patron.loans.dueDate` (#35)
- [x] title/author/call number (sortable/display versions) `patron.loans.item.title`, `patron.loans.item.author`, `patron.loans.item.item.effectiveCallNumberComponents` ?
- [x] when was it borrowed `patron.loans.loanDate` (#35)
- [x] renewable ((loan policy > renewalsPolicy > numberAllowed) (#34)
- [x] The date in which the item can be renewed (i.e too soon to renew) - (loan policy > renewalsPolicy > magic)  (#34)
- [x] The period before the due date in which the item can be renewed - (loan policy > renewalsPolicy > magic)  (#34)
- [ ] when was it renewed (#35)
- [ ] when was it recalled (#35)
- [x] accrued (estimated overdue amount) (`patron > loans > details > feesAndFines`?)
- [x] library (`patron > loans > details > itemEffectiveLocationAtCheckOut > library`?)
- [ ] from ILL? (https://github.com/sul-dlss/mylibrary/issues/833)
- [ ] from ILB?
- [ ] form Borrow Direct?
- [x] short term loan? (depends on loan_period_type)  (#34)
- [x] circulation rule
- [x] reserve item? (previously: circulation_rule&.end_with?('-RES'))  (#34)
- [x] unseen_renewals_remaining, seen_renewals_remaining (no such thing in FOLIO)
- [ ] original_due_date (#35)
- [x] barcode `patron.loans.item.item.barcode`
- [x] catkey for "view in searchworks link" `patron.loans.item.instance.hrid` (without leading letters)

# requests
(for each request)
- [x] is it ready for pickup? `patron.holds.status`
- [x] pickup location `patron.holds.pickupLocation.name`
- [x] expiration date `patron.holds.expirationDate`
- [ ] fill by date (https://github.com/sul-dlss/mylibrary/issues/834)
- [x] title/author/call number (sortable/display versions) `patron.holds.item.title`, `patron.holds.item.author`, `patron.holds.item.item.effectiveCallNumberComponents` ?
- [x] waitlist position `patron.holds.queuePosition` (although you don't know total # in queue)
- [x] catkey for "view in searchworks link" `patron.holds.item.instance.hrid` (without leading letters)

# fines
(for each fine)
- [x] reason (part of Charge)
- [x] amount (part of Charge)
- [x] title/author/call number (sortable/display versions) (yes, we have 'item' within Charge)
- [x] date billed (? we have 'accrualDate' from Charge) (#46)
- [ ] processing fee (? we have 'feeFineType' from FeeFine -- is there a processing fee type?)
- [ ] library (what does it mean when this just says "SUL"? same as checkout source?) (?, we have 'item' within Charge) (#46)
- [ ] library contact email? we do this with a lookup/helper now (?, we have 'item' within Charge)

**Comment by jgreben** [comment]
For `fines` we will also need to get the ids of each account charge so we can pass these to CyberSource and have them returned and reconciled using the post to the same api. See: 

- https://s3.amazonaws.com/foliodocs/api/mod-feesfines/p/accounts.html#accounts__accountid__get
- https://s3.amazonaws.com/foliodocs/api/mod-feesfines/p/accounts.html#accounts__accountid__pay_post

**Comment by cbeer** [comment]
Remaining work has been split off into smaller tickets.
