### ISSUE TITLE
Track down where to find tracking information about a due date

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/folio-graphql#35]
We want to display some tracking information about an items due date, including:

- [x] the due date (`patron.loans.dueDate`)
- [x] when was it borrowed `patron.loans.loanDate`
- [ ] if an item was recalled, and when it was recalled
- [ ] if an item was renewed, and when it was last renewed
- [ ] the item's original due date

**Comment by thatbudakguy** [comment]
recalls and renewals can use the [`/loan-storage/loan-history`](https://s3.amazonaws.com/foliodocs/api/mod-circulation-storage/r/loan-storage.html#loan_storage_loan_history_get) API with a CQL query filtering on both the loan ID and the action type. a response with one event in the log (a renewal) for a given loan would look like:
```js
  "loansHistory": [
    {
      "id": "29abc628-3712-48ba-b01f-f8b00c15dd61",
      "operation": "I",
      "createdDate": "2017-03-01T22:34:11+00",
      "loan": {
        "id": "cf23adf0-61ba-4887-bf82-956c4aae2260",
        "userId": "df7f4993-8c14-4a0f-ab63-93975ab01c76",
        "proxyUserId": "346ad017-dac1-417d-9ed8-0ac7eeb886aa",
        "itemId": "cb20f34f-b773-462f-a091-b233cc96b9e6",
        "loanDate": "2017-03-01T22:34:11+00:00",
        "dueDate": "2017-04-15T22:34:11+00:00",
        "status": {
          "name": "Open"
        },
        "action": "renewed",
        "itemStatus": "Checked out",
        "renewalCount": 1
      }
    },
]
```


there is also a boolean `dueDateChangedByRecall` on the loan itself, indicating if a recall resulted in the due date being moved up.

**Comment by thatbudakguy** [comment]
you might be able to get the original due date by finding the initial checkout event for the loan using the loan history API and using that `dueDate` (if `dueDateChangedByRecall` is `true`; otherwise you can just use whatever the latest `dueDate` is).

the API docs note that the `action` field:
> ...currently can be any value, values commonly used are checkedout and checkedin

`renewed` and `recalled` also seem to be valid values.

**Comment by cbeer** [comment]
> currently can be any value

😭

**Comment by cbeer** [comment]
Checking the loan history seems a little icky, but I've transferred this research into https://github.com/sul-dlss/mylibrary/issues/825 for implementation.
